In [1]:
import numpy as np
arr =np.array([1,2,3,4,5])
print(arr)    #print array elements
print(arr[0]) #acessing by index
print(arr[1:3]) #slicing

[1 2 3 4 5]
1
[2 3]


In [8]:
#creating arry giving i/p as list,tuple,dictionary,set
list =['a','e','i','o','u']
arr =list
print(arr)
tuple=("bhagya","jyoti","Shree")
arr = tuple
print(arr)
dictionary ={ 'home': 'key' ,'river': 'water','well':'pot'}
arr=dictionary
print(arr)
set= {"apple","banana","grapes"}
arr=set
print(arr)

['a', 'e', 'i', 'o', 'u']
('bhagya', 'jyoti', 'Shree')
{'home': 'key', 'river': 'water', 'well': 'pot'}
{'banana', 'grapes', 'apple'}


In [42]:
#append elements at end
arr=np.array([1,2,3,4,5])
print(arr)
arr1=np.append(arr,7,axis=45)
print(arr1)
#insert 
arr3=np.array([9,8,7])
arr2=np.insert(arr3,0,arr,axis=0)
print(arr2)

[1 2 3 4 5]
[1 2 3 4 5 7]
[1 2 3 4 5 9 8 7]


In [47]:
#slicing
arr=np.array(['b','h','a','g','y','a','s','h','r','e','e'])
print(arr[1:-1])
print(arr[4:])
print(arr[:6])
print(arr[2:6])

['h' 'a' 'g' 'y' 'a' 's' 'h' 'r' 'e']
['y' 'a' 's' 'h' 'r' 'e' 'e']
['b' 'h' 'a' 'g' 'y' 'a']
['a' 'g' 'y' 'a']
