In [39]:
import numpy as np
#create array using specific functions
arr=np.zeros(4)
print(arr)
arr1=np.ones(7)
print(arr1)
arr2=np.random.rand(2)
print(arr2)

[0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1.]
[0.62697322 0.39174132]


In [41]:
# create multidimensional array
arr_2dim=np.array([[1,2,3],[4,5,6],[7,8,9]]) # 3rows with 3 columns
print(arr_2dim)
#access 2dimension arr by index
print("3rd element of 2nd row:",arr_2dim[1,2]) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]
3rd element of 2nd row: 6


In [51]:
#sum of all elements
print(np.sum(arr_2dim))
#calulate mean of each row
print(np.mean(arr_2dim,axis=1)) #each row
print(np.mean(arr_2dim)) #all rows
print(np.mean(arr_2dim,axis=0)) # each coloumn

45
[2. 5. 8.]
5.0
[4. 5. 6.]
